### ISSUE TITLE
Support macOS Big Sur and Apple Silicon hardware platform

### ISSUE THREAD

**Issue by chomatdam** [javascriptdata/danfojs#201]
This issue is to track the progress of the Apple Silicon hardware support.

Tensorflow recently released it with [v2.5.0](https://github.com/tensorflow/tensorflow/releases/tag/v2.5.0).

Tfjs is tracking this hardware support with [this issue](https://github.com/tensorflow/tfjs/issues/4514) and will probably get an update soon.

Danfojs is currently using `"@tensorflow/tfjs-node": "3.3.0"`.

As soon as we get an update for `@tensorflow/tfjs-node`, danfojs can version bump the dependency and be used on new Apple devices.

**Comment by stordopoulos** [comment]
@chomatdam, are there any updates on this issue? I still get a ```Unsupported system: cpu-darwin-arm64``` message.

**Comment by steveoni** [comment]
@chomatdam can you show the full error response you recieved.

**Comment by GKjohns** [comment]
Have there been any updates here? Given that apple silicon isn't going away, there's a lot of potential impact in fixing the issue

**Comment by risenW** [comment]
> Same here, the full error is this:
> 
> ```
> Exit code: 1
> Command: node scripts/install.js
> Arguments: 
> Directory: /*path-to-the-project*/node_modules/danfojs-node/node_modules/@tensorflow/tfjs-node
> Output:
> CPU-darwin-3.6.1.tar.gz
> * Downloading libtensorflow
> /*path-to-the-project*/node_modules/danfojs-node/node_modules/@tensorflow/tfjs-node/scripts/install.js:102
>     throw new Error(`Unsupported system: ${libType}-${platform}-${os.arch()}`);
>           ^
> 
> Error: Unsupported system: cpu-darwin-arm64
> ```
> 
> It seems to be related to the installation scripts of `@tensorflow/tfjs-node` see [here](https://github.com/tensorflow/tfjs/issues/4514).
> 
> Can we make this library a peer dependency so that can be updated as needed? My proposition makes sense?

Great suggestion, but making this a peer dependency does not solve the current issue.

**Comment by risenW** [comment]
> Have there been any updates here? Given that apple silicon isn't going away, there's a lot of potential impact in fixing the issue

Sadly no official fix yet, but I keep tracking this [issue](https://github.com/tensorflow/tfjs/issues/4514) for any.

**Comment by jamg44** [comment]
> > Have there been any updates here? Given that apple silicon isn't going away, there's a lot of potential impact in fixing the issue
> 
> Sadly no official fix yet, but I keep tracking this [issue](https://github.com/tensorflow/tfjs/issues/4514) for any.

It seems to be fixed [now](https://github.com/tensorflow/tfjs/issues/4514#issuecomment-999022255)
