### ISSUE TITLE
Handling large data

### ISSUE THREAD

**Issue by pandichef** [javascriptdata/danfojs#223]
**Is your feature request related to a problem? Please describe.**
When I load a 4GB CSV file using read_csv, I see this:
File size (4591820193) is greater than possible Buffer: 2147483647 bytes

**Describe the solution you'd like**
Handle larger data sets

**Comment by risenW** [comment]
I plan to work on these issue in the new version we are working on here #235

**Comment by risenW** [comment]
We added a couple of stream data processing functionality in the latest Typescript release. See: https://danfo.jsdata.org/api-reference/general-functions/danfo.streamcsvtransformer

If you need help migrating to the latest version, see: https://danfo.jsdata.org/examples/migrating-to-the-stable-version-of-danfo.js
