### ISSUE TITLE
Typing issue with void functions

### ISSUE THREAD

**Issue by mebibou** [javascriptdata/danfojs#294]
**Describe the bug**

When using typescript and operation like `drop`, it cannot be chained directly to another operation or the compiler will throw an error like `Property 'to_csv' does not exist on type 'void | DataFrame'.\n  Property 'to_csv' does not exist on type 'void'.`

**To Reproduce**

```typescript
import { DataFrame } from 'danfojs-node';

const df = new DataFrame([]);
df.drop({ columns, inplace: false }).to_csv();
```

**Expected behavior**

It should return `void` only when using `inplace: true`. Currently it assumes it could be both, but the parameters should infer which return type it expects.

Typescript version `3.9.10` and `danfojs-node` version `0.3.3` used

**Comment by risenW** [comment]
@mebibou Have you tried this:

`df.drop({ columns, inplace: false })?.to_csv(); `

**Comment by risenW** [comment]
FIXED and released in the latest TS version.

If you need help migrating to the latest version, see: https://danfo.jsdata.org/examples/migrating-to-the-stable-version-of-danfo.js
