### ISSUE TITLE
groupby error

### ISSUE THREAD

**Issue by mserranomartin** [javascriptdata/danfojs#310]
**Describe the bug**
I get a `Column names length mismatch` error when trying to group by one column. If I try the same thing in Pandas everything works as it should.

**To Reproduce**
```
dfd.read_csv('https://raw.githubusercontent.com/homomorfismo/spain-university-cutoffs/main/databases/spain_utf8.csv').then(a => df)
df.groupby(['University'])
```

**Expected behavior**
Obtaining a list of dataframes each of which only contains observations with the same University value. 

**Screenshots**
![2021-11-06 (1)](https://user-images.githubusercontent.com/63246434/140625840-affdd949-ad04-44f7-be16-ff64a22f27c5.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 95.0.4638.69 (64 bits)

**Comment by risenW** [comment]
@steveoni Can you take a look at this.

**Comment by Teut2711** [comment]
`
        const testsDf = await read_excel("./case7.xlsx");
        testsDf.addColumn({ "column": "AgeGroup", "values": testsDf["Age"].apply(x => Number(x) > 40 ? "old" : "young"), inplace: true })
        testsDf.drop({
            columns: ["Age",
                'Patient Name',
                'MRN',
                'Result Value'
            ], inplace: true
        })

        let testsGroupBy = testsDf.groupby(["Location", "Dept", "Gender", "AgeGroup", "Test Name"])

`


ParamError: Column names length mismatch. You provided a column of length 8 but Ndframe columns has lenght of 7

**Comment by Teut2711** [comment]
It looks like I am facing catching issue with node. Sorry.

**Comment by Teut2711** [comment]
It looks like undefined is filtered from row which makes the length  lesser.

**Comment by steveoni** [comment]
@homomorfismo i think the way you write the code is not correct

```js
dfd.read_csv('https://raw.githubusercontent.com/homomorfismo/spain-university-cutoffs/main/databases/spain_utf8.csv')
   .then(df => {
        let c = df.groupby(['University']);
    });
```

**Comment by homomorfismo** [comment]
@steveoni I get the same exact error

**Comment by steveoni** [comment]
@homomorfismo that's weird... i tried same thing without any issue. can i see your code?

**Comment by stevenjchang** [comment]
I get the same error
I'm using `"danfojs": "0.3.3"`

<img width="628" alt="Screen Shot 2021-11-17 at 1 50 00 PM" src="https://user-images.githubusercontent.com/13124244/142288324-cf6d6178-ee60-4b96-a24f-6d28e8620b0a.png">

```
async function getData() {
  const df = await dfd.read_csv('./csv/data1.csv');
   df.print();
  const grp = df.groupby(['Record Type']);
}
```

For more context, the code works when I use a dummy dataset, like the `titantic.csv` file found in the tutorial https://danfo.jsdata.org/examples/titanic-survival-prediction-using-danfo.js-and-tensorflow.js

If I log out `df.axis` it does show 48 columns in the df
<img width="594" alt="Screen Shot 2021-11-17 at 2 18 51 PM" src="https://user-images.githubusercontent.com/13124244/142291737-b4121b9f-cb3e-4a22-a03a-30089f4a6f76.png">

**Comment by homomorfismo** [comment]
> @homomorfismo that's weird... i tried same thing without any issue. can i see your code?

I copypasted yours. I use chrome's console, load the danfo library in an html file and run the line.

**Comment by steveoni** [comment]
> > @homomorfismo that's weird... i tried same thing without any issue. can i see your code?
> 
> I copypasted yours. I use chrome's console, load the danfo library in an html file and run the line.

i'm actually using the node enviroment, have you tried that out to see if it works

```js
const dfd = require("danfojs-node")
dfd.read_csv('https://raw.githubusercontent.com/homomorfismo/spain-university-cutoffs/main/databases/spain_utf8.csv')
   .then(df => {
	let c = df.groupby(['University']);
   });
```

**Comment by steveoni** [comment]
> I get the same error I'm using `"danfojs": "0.3.3"`
> 
> <img alt="Screen Shot 2021-11-17 at 1 50 00 PM" width="628" src="https://user-images.githubusercontent.com/13124244/142288324-cf6d6178-ee60-4b96-a24f-6d28e8620b0a.png">
> 
> ```
> async function getData() {
>   const df = await dfd.read_csv('./csv/data1.csv');
>   df.print();
>   const grp = df.groupby(['Record Type']);
> }
> ```
> 
> For more context, the code works when I use a dummy dataset, like the `titantic.csv` file found in the tutorial https://danfo.jsdata.org/examples/titanic-survival-prediction-using-danfo.js-and-tensorflow.js
> 
> If I log out `df.axis` it does show 48 columns in the df <img alt="Screen Shot 2021-11-17 at 2 18 51 PM" width="594" src="https://user-images.githubusercontent.com/13124244/142291737-b4121b9f-cb3e-4a22-a03a-30089f4a6f76.png">

@stevenjchang can you try using a lower version and see if it works (to be sure if it's this version)

**Comment by risenW** [comment]
FIXED and released in the latest TS version.

If you need help migrating to the latest version, see: https://danfo.jsdata.org/examples/migrating-to-the-stable-version-of-danfo.js
