### ISSUE TITLE
TF does't work on Mac M1 - Please update TF

### ISSUE THREAD

**Issue by habitsAI** [javascriptdata/danfojs#318]
**Describe the bug**
By install danfo and tensorflow on Mac M1 processors can´t work . 

Now TF fix the bug you only have to update library please.

https://github.com/tensorflow/tfjs/pull/5899

**To Reproduce**
1. Go to 'Mac M1 Chip '
2. Try to npm install danfojs 
3. See error

**Expected behavior**
Will download and install dependences correctly

**Desktop (please complete the following information):**
 - OS: Mac Os Monterrey
 - NodeJS 14+, NPM 6+

Solved issue
https://github.com/tensorflow/tfjs/pull/5899

**Comment by risenW** [comment]
> **Describe the bug** By install danfo and tensorflow on Mac M1 processors can´t work .
> 
> Now TF fix the bug you only have to update library please.
> 
> [tensorflow/tfjs#5899](https://github.com/tensorflow/tfjs/pull/5899)
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to 'Mac M1 Chip '
> 2. Try to npm install danfojs
> 3. See error
> 
> **Expected behavior** Will download and install dependences correctly
> 
> **Desktop (please complete the following information):**
> 
> * OS: Mac Os Monterrey
> * NodeJS 14+, NPM 6+
> 
> Solved issue [tensorflow/tfjs#5899](https://github.com/tensorflow/tfjs/pull/5899)

I’m aware of this, and have been tracking this on this issue #201 

If this has been fixed , then that’s great news, I’ll look into it and do any update needed.

**Comment by rzykov** [comment]
It seems it fixed in tfjs
https://github.com/javascriptdata/danfojs/issues/201#issuecomment-1013903036

**Comment by risenW** [comment]
Looking into it now
