### ISSUE TITLE
RFC: Time series. Could they be first-class citizens just like they are in Pandas?

### ISSUE THREAD

**Issue by kfern** [javascriptdata/danfojs#321]
**Is your feature request related to a problem? Please describe.**

Currently dates/times are treated as strings and lacks support for time zones, there are some related issues like #308 and being able to properly manage time series is important in certain domains.

Could they be first-class citizens just like they are in Pandas? 

**Describe the solution you'd like**

An initial idea could be:

Accept as input any valid date string in Javascript (no breaking changes)
Values stored as UTC timestamps
Typed as DateTime or similar
Printed using string formats and time zones
Time zones optional

**Describe alternatives you've considered**

We could use a specialized library like https://js-joda.github.io/js-joda/ 

"... js-joda is a standalone date and time implementation.

The API has a domain-driven design with classes for each of the different use cases, like LocalDate, ZonedDateTime or Period"

**Additional context**
[Pandas Time series / date functionality](https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html)

**Comment by risenW** [comment]
Makes sense!, thanks for the suggestion, I'll look into this.

**Comment by kfern** [comment]
Closed by #511
