### ISSUE TITLE
read_excel with file object source

### ISSUE THREAD

**Issue by Lu-David** [javascriptdata/danfojs#339]
I noticed in the danfojs docs that the read_excel method only takes in a string for the file path or url. The other methods, read_csv and read_json, both can read in file objects. 

Would it be possible to add functionality to read_excel so that it can also read from a file object to dataframe? I'm wondering if there were any issues regarding implementing this functionality in the first place?

Thanks!

**Comment by risenW** [comment]
@Lu-David read_excel also supports loading of file objects, we probably missed adding that in the documentation.

**Comment by risenW** [comment]
Update: Documentation has been updated! https://danfo.jsdata.org/api-reference/input-output/danfo.read_excel#reading-an-input-file-object-in-the-browser
