### ISSUE TITLE
Groupby.std() missing

### ISSUE THREAD

**Issue by Devwulf** [javascriptdata/danfojs#344]
So, I've been updating my codebase to use the version 1.0.0 of Danfo JS. But apparently the Groupby.std() function is now missing. I've checked the code and the std operation is still supported. Perhaps a public function for it was forgotten to be included?

**Comment by risenW** [comment]
@steveoni Can you confirm this.

**Comment by steveoni** [comment]
@risenW @Devwulf thats true. The code for std was implemented in the arithmetic logic, but the method was not created to expose it. I will add that

**Comment by Devwulf** [comment]
@risenW @steveoni Could I work on this instead? I really need this feature as soon as possible so I can finally deploy my project.

**Comment by steveoni** [comment]
@Devwulf you can go ahead to fix it.

**Comment by risenW** [comment]
> @risenW @steveoni Could I work on this instead? I really need this feature as soon as possible so I can finally deploy my project.

Thanks for flagging and fixing this, I have pushed a new release (v.1.0.1)
