### ISSUE TITLE
DataFrame.rename() mapper arg should be typed instead of any

### ISSUE THREAD

**Issue by Devwulf** [javascriptdata/danfojs#345]
In version 1.0.0, the DataFrame.rename() mapper argument is typed as any instead of strongly typed. This caused me to completely miss the fact that the mapper argument is now outside the options argument while migrating to this new version of Danfojs, and it may lead others to do so as well. Wouldn't it be better to type it something like this?

```js
type Mapper = {
    [index: string]: string | number;
}
```

**Comment by risenW** [comment]
@Devwulf Good point. Would you like sending a PR?

**Comment by Devwulf** [comment]
> @Devwulf Good point. Would you like sending a PR?

Sure, I'll get on it tomorrow morning!
