### ISSUE TITLE
New methods `iat` and `at` to access single value in DataFrame/Series

### ISSUE THREAD

**Issue by risenW** [javascriptdata/danfojs#349]
Regarding your point on: 
> Should I be using a different method just to get the single value of cell X/Y?

I think we need to add a new method for that. Something like `[iat](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iat.html)` in pandas. I'll create an issue for it.

_Originally posted by @risenW in https://github.com/javascriptdata/danfojs/discussions/348#discussioncomment-1970316_

## Acceptance
* [ ] `iat` method exists and supports retrieving single values by row and/or column index
* [ ] `at` method exists and supports retrieving single values by row and/or column labels

**Comment by KingWebsites** [comment]
Great news. Could you add an "at" method too, which is the same but uses named row and column labels?
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.at.html

**Comment by risenW** [comment]
@KingWebsites Would like to work on this?

**Comment by KingWebsites** [comment]
Unfortuately I don't have the skillset to contribute. After years as a front-end dev who just used jQuery I've only spent a few months learning more modern js. I'm hoping to be in a position to do so at some point in the future though.

**Comment by risenW** [comment]
> Unfortuately I don't have the skillset to contribute. After years as a front-end dev who just used jQuery I've only spent a few months learning more modern js. I'm hoping to be in a position to do so at some point in the future though.

No worries at all 👏🏻Thanks for using the library and taking out time to give us feedback. It is also a very important contribution.
