### ISSUE TITLE
Counting the number of rows

### ISSUE THREAD

**Issue by codeheart09** [javascriptdata/danfojs#350]
Hi guys,

What is the best way to count the number of rows in the dataframe?

I'm using `df.values.length`, but I don't know if there is another option without having to access the values array.

I thought `df.size` would do that, but it seems to return the total number of cells, not rolls.

PS: the `Dataframe.size` attribute link is broken in the documentation.
https://danfo.jsdata.org/api-reference/dataframe

**Comment by steveoni** [comment]
df.shape[0]

**Comment by steveoni** [comment]
df.size should return an array of number of rows and columns

**Comment by steveoni** [comment]
I mean df.shape, 

for rows df.shape[0] @codeheart09
