### ISSUE TITLE
Add dt.date

### ISSUE THREAD

**Issue by Emporea** [javascriptdata/danfojs#356]
Coming from pandas, it seems inconvinient that dt.date is missing from all the datetime functions. Is there a reason for that?
Would be awesome if this could be added.

`2022-01-17T00:00:00Z > dt.date > 2022-01-17`

**Comment by risenW** [comment]
> 

Hi, there's no major reason for excluding this other than we forgot to add it. It's quite easy and definitely a good first issue.

**Comment by Emporea** [comment]
`df["date"].dt.date().print();`

gives invalid dates:

![image](https://user-images.githubusercontent.com/21969523/150152535-43623d95-3d0b-4ce4-889c-eb20fe638003.png)

**Comment by Emporea** [comment]
danfojs: 
```
let index = ["0", "1", "2", "3"];
let value = [
    "2018-11-30T20:59:00",
    "2018-10-30T20:59:00",
    "2018-09-30T20:59:00",
    "2018-08-30T20:59:00",
];

let sf = new danfo.Series(value, { index });
sf = danfo.toDateTime(sf);
console.log(sf.date());
```

gives

```
'11/30/2018, 8:59:00 PM',
'10/30/2018, 8:59:00 PM',
'9/30/2018, 8:59:00 PM',
'8/30/2018, 8:59:00 PM'
```

while pandas:

```
index = ["0", "1", "2", "3"]
value = [
    "2018-11-30T20:59:00",
    "2018-10-30T20:59:00",
    "2018-09-30T20:59:00",
    "2018-08-30T20:59:00",
]

sf = pd.Series(value, index)
sf = pd.to_datetime(sf)
sf.dt.date
```

gives

```
2018-11-30
2018-10-30
2018-09-30
2018-08-30
```

This is not what date() is supposed to be.

**Comment by risenW** [comment]
> danfojs:
> 
> ```
> let index = ["0", "1", "2", "3"];
> let value = [
>     "2018-11-30T20:59:00",
>     "2018-10-30T20:59:00",
>     "2018-09-30T20:59:00",
>     "2018-08-30T20:59:00",
> ];
> 
> let sf = new danfo.Series(value, { index });
> sf = danfo.toDateTime(sf);
> console.log(sf.date());
> 
> ---
> 
> '11/30/2018, 8:59:00 PM',
> '10/30/2018, 8:59:00 PM',
> '9/30/2018, 8:59:00 PM',
> '8/30/2018, 8:59:00 PM'
> ```
> 
> while pandas:
> 
> ```
> index = ["0", "1", "2", "3"]
> value = [
>     "2018-11-30T20:59:00",
>     "2018-10-30T20:59:00",
>     "2018-09-30T20:59:00",
>     "2018-08-30T20:59:00",
> ]
> 
> sf = pd.Series(value, index)
> sf = pd.to_datetime(sf)
> print(sf.dt.date)
> 
> ---
> 
> 2018-11-30
> 2018-10-30
> 2018-09-30
> 2018-08-30
> ```
> 
> This is not what date() is supposed to be.

We are using the Standard JavaScript Date under the hood. Peculiarities like the sep `/` and extra time properties can be easily formatted since the result is a String. 

We use JS standard Date and do not want to deviate or create a custom Date implementation similar to Pandas but different from JS standard.

**Comment by Emporea** [comment]
Yes you are probably right.
