### ISSUE TITLE
Error returned when passing only one value to DataFrame.loc

### ISSUE THREAD

**Issue by chrisg44** [javascriptdata/danfojs#364]
**Describe the bug**
This seems way to be way to obvious to actually be a bug and there is definitely potential I'm just using it wrong (only recently started using Danfo) - but at the very least the error handling is unhelpful.

When passing only one row value to DataFrame.loc it returns a "Uncaught Error: IndexError: Specified index (a) not found" irrespective of what value is passed. For example I could pass ["a", "b"] and that would work fine but ["a"] would return the above error; I have tried passing the single value as a string i.e. "a" but that returns "Uncaught Error: rows parameter must be an Array. For example: rows: [1,2] or rows: ["0:10"]" .

**To Reproduce**
To test this I took the same code from https://danfo.jsdata.org/api-reference/dataframe/danfo.dataframe.loc#index-by-specific-rows-and-return-all-columns.

##HTML

```
<script src="https://cdn.jsdelivr.net/npm/danfojs@1.0.1/lib/bundle.min.js"></script>
<script src="app.js"></script>
```

##Javascript

```
let data = { "Name": ["Apples", "Mango", "Banana", "Pear"],
"Count": [21, 5, 30, 10],
"Price": [200, 300, 40, 250] }

let df = new dfd.DataFrame(data, {index: ["a", "b", "c", "d"]})
df.print()

//Case 1
let sub_df1 = df.loc({rows: ["a", "b"]})
sub_df1.print()

//Case 2
let sub_df2 = df.loc({rows: ["a"]})
sub_df2.print()

//Case 3
let sub_df3 = df.loc({columns: ["Name", "Count"]})
sub_df3.print()

//Case 4
let sub_df4 = df.loc({columns: ["Name"]})
sub_df4.print()
```

**Expected behavior**
It would be expected that all of the above would print to console (or at least return an error of incorrect use); however Case 2 returns the error "Uncaught Error: IndexError: Specified index (a) not found"; Cases 1,3,4 all work as expected.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome 
 - Version 97

**Comment by risenW** [comment]
> https://danfo.jsdata.org/api-reference/dataframe/danfo.dataframe.loc#index-by-specific-rows-and-return-all-columns

Not a bug, just some subtlety in `loc` row indexing. You need to explicitly quote a row index of it's an alphabet:
It was documented here: 
```javascript
let sub_df4 = df.loc({ rows: ["a"] }) //Won't work ❌
let sub_df4 = df.loc({ rows: [`"a"`] }) // works ✅
sub_df4.print()
```

**Comment by chrisg44** [comment]
Thanks - appreciated for getting back to me so promptly. I'm actually using a non-alphabetic index - but that works for that as well. Just for clarity as this seems to leave an odd implementation where you have to check for arrays of length one (unless I misunderstand how to implement).

In my application I don't know the length of the array that will be passed in (only that it will contain between one and all of the index values). So based on the above suggestion I would have to implement something like:

```
let data = { "Name": ["Apples", "Mango", "Banana", "Pear"],
"Count": [21, 5, 30, 10],
"Price": [200, 300, 40, 250] }

let df = new dfd.DataFrame(data, {index: ["alpha", "beta", "charlie", "deta"]})
df.print()

let list = either ["alpha"] or ["alpha", "beta"]

if (list.length === 1) {
    // convert ["alpha"] to [`"alpha"`]
}

let sub_df1 = df.loc({rows: list})
sub_df1.print()
```

**Comment by risenW** [comment]
> Thanks - appreciated for getting back to me so promptly. I'm actually using a non-alphabetic index - but that works for that as well. Just for clarity as this seems to leave an odd implementation where you have to check for arrays of length one (unless I misunderstand how to implement).
> 
> In my application I don't know the length of the array that will be passed in (only that it will contain between one and all of the index values). So based on the above suggestion I would have to implement something like:
> 
> ```
> let data = { "Name": ["Apples", "Mango", "Banana", "Pear"],
> "Count": [21, 5, 30, 10],
> "Price": [200, 300, 40, 250] }
> 
> let df = new dfd.DataFrame(data, {index: ["alpha", "beta", "charlie", "deta"]})
> df.print()
> 
> let list = either ["alpha"] or ["alpha", "beta"]
> 
> if (list.length === 1) {
>     // convert ["alpha"] to [`"alpha"`]
> }
> 
> let sub_df1 = df.loc({rows: list})
> sub_df1.print()
> ```

Yes, that’s a good way to do it.

**Comment by kitfit-dave** [comment]
Sorry to comment on a closed issue, but I was just foiled for some time by this.
If it is true that string indexes must be quoted, why do they only need to be quoted if there is only one? Why can't they be quoted when there are multiple?

i.e. (as mentioned above)
```
df.loc({ rows: ['"a"'] }).print() // this does work
df.loc({ rows: ['"a"', '"c"'] }).print() // but then not this
```

This seems an odd interface to have, that is one thing, but it's also pretty much undocumented. It could at least be called out in the docs.

If the code in indexing.js could just behave the same way while "parsing" the indexes when the array is 1 in length (line 199 `_index.indexOf(Number(rows[0]))`) and when it is more (line 254 `_index.indexOf(rows[i])`)
You would still need to call Number to find the index if it is indeed a number passed as a string, but that call is also missing from the multiple indexes case, e.g.:

```
df.loc({ rows: ['1', '2'] }).print() // this doesn't work
```

Summary:
input types could be: [1] or ["1"] or ["a"] or [1, 2] or ["1", "2"] or ["a", "b"] or [true, false]
I think it's important to point out that quoted values can be alphanumeric or Number, using "1" all the time in the docs is confusing (when you mean it's sometimes Number("1") and sometimes just the string "1" - you can check both in indexing.js

talking about confusing, this is in the docs on loc: 
```
Allowed inputs for are:
- An integer, e.g. "r1".
- A list or array of integers, e.g. ["a", "b", "d"].
```
an integer "r1" ? or "a"?

**Comment by ZandercraftGames** [comment]
> Sorry to comment on a closed issue, but I was just foiled for some time by this. If it is true that string indexes must be quoted, why do they only need to be quoted if there is only one? Why can't they be quoted when there are multiple?
> 
> i.e. (as mentioned above)
> 
> ```
> df.loc({ rows: ['"a"'] }).print() // this does work
> df.loc({ rows: ['"a"', '"c"'] }).print() // but then not this
> ```
> 
> This seems an odd interface to have, that is one thing, but it's also pretty much undocumented. It could at least be called out in the docs.
> 
> If the code in indexing.js could just behave the same way while "parsing" the indexes when the array is 1 in length (line 199 `_index.indexOf(Number(rows[0]))`) and when it is more (line 254 `_index.indexOf(rows[i])`) You would still need to call Number to find the index if it is indeed a number passed as a string, but that call is also missing from the multiple indexes case, e.g.:
> 
> ```
> df.loc({ rows: ['1', '2'] }).print() // this doesn't work
> ```
> 
> Summary: input types could be: [1] or ["1"] or ["a"] or [1, 2] or ["1", "2"] or ["a", "b"] or [true, false] I think it's important to point out that quoted values can be alphanumeric or Number, using "1" all the time in the docs is confusing (when you mean it's sometimes Number("1") and sometimes just the string "1" - you can check both in indexing.js
> 
> talking about confusing, this is in the docs on loc:
> 
> ```
> Allowed inputs for are:
> - An integer, e.g. "r1".
> - A list or array of integers, e.g. ["a", "b", "d"].
> ```
> 
> an integer "r1" ? or "a"?

I've been trying the same thing with iloc and no matter what I try to put into it, a number, a string, a range, etc. it always gives me "Error: rows parameter must be an Array. For example: rows: [1,2] or rows: ["0:10"]"
