### ISSUE TITLE
Length error when filtering by array with df.query and df['column'].ne

### ISSUE THREAD

**Issue by joshuakoh1** [javascriptdata/danfojs#375]
**Describe the bug**
```
removeDates = ['220201', '220202'];
OR
removeDates = new dfd.Series(['220201', '220202']);

dfc.query(df['dates'].ne(removeDates),{"inplace": true});
```
df is a 5000 row DF
```
series.js:1468 
        
       Uncaught Error: LengthError: Lenght of other must be equal to length of Series
    at Series.boolOps (series.js:1468:13)
    at Series.ne (series.js:1417:17)
```

**Expected behavior**
Filters all the rows where date not in list

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Edge]
 - Version [97]
 - Danfo 1.0.2

**Comment by risenW** [comment]
> **Describe the bug**
> 
> ```
> removeDates = ['220201', '220202'];
> OR
> removeDates = new dfd.Series(['220201', '220202']);
> 
> dfc.query(df['dates'].ne(removeDates),{"inplace": true});
> ```
> 
> df is a 5000 row DF
> 
> ```
> series.js:1468 
>         
>        Uncaught Error: LengthError: Lenght of other must be equal to length of Series
>     at Series.boolOps (series.js:1468:13)
>     at Series.ne (series.js:1417:17)
> ```
> 
> **Expected behavior** Filters all the rows where date not in list
> 
> **Desktop (please complete the following information):**
> 
> * OS: [Windows]
> * Browser [Edge]
> * Version [97]
> * Danfo 1.0.2

Arguments passed to the `.ne` operator must be of the same length. That means the length of `df['dates']` must be the same as `removeDates` before you can compare them.
