### ISSUE TITLE
Error: File format not supported! when accessing column with null as first value in danfojs-node

### ISSUE THREAD

**Issue by staznz** [javascriptdata/danfojs#376]
When attempting to access a columns where the **first** value is null, (corresponding to empty value in csv), I get a `File format not supported!` error.

**To Reproduce**
```
const df = await dfd.readCSV(<path to my csv>);
df[<column containing null values>].print();
```

**Expected behavior**
To print column without crashing.

**Desktop**
 - OS: Mac OS 11.4
 - Node: v16.13.0
 - danfojs-node: v1.0.2

**Comment by risenW** [comment]
Thanks for raising this issue, I just confirmed it as well. I'll work on a fix ASAP.
