### ISSUE TITLE
No maximum function of columns per groups

### ISSUE THREAD

**Issue by brunsky** [javascriptdata/danfojs#378]
There is no "max" in the opsName list.

https://github.com/javascriptdata/danfojs/blob/0d33e344b80a3ed54c91c9393ac3b583d4b0b1a4/src/danfojs-base/aggregators/groupby.ts#L233

If I need to obtain maximum value then I will get "group operation: max is not valid".
Is there any reason not to let "max" in?

**Comment by steveoni** [comment]
@brunsky max was mixing in the first built, but its now added

https://github.com/javascriptdata/danfojs/blob/a39fd4a75bc3006a5a5c8a38ab51cf3ce3576bee/src/danfojs-base/aggregators/groupby.ts#L234
