### ISSUE TITLE
File format not supported! - Exception raises when creating a Serie or DataFrame with a leading null value 

### ISSUE THREAD

**Issue by alexebl** [javascriptdata/danfojs#379]
This code reproduce the error: 

const obj_data = [null, 'bval2', 'bval3', 'bval4'];
const ds = new dfd.Series(obj_data, {dtypes: ['string']});

In production environment its very common to have missing data. 
If data is missing somewhere in the array it seems to work correctly, but in case of first value it raises the exception: File format not supported!

**Comment by risenW** [comment]
> const obj_data = [null, 'bval2', 'bval3', 'bval4'];
> const ds = new dfd.Series(obj_data, {dtypes: ['string']});

Interesting, thanks for raising this. It's a subtle issue, which our test did not catch. For example, placing the `null` value in any other position besides the first works fine. 

I'll fix this ASAP!
