### ISSUE TITLE
remove nodejs api depedencies in order to support webpack5 and other bundlers.

### ISSUE THREAD

**Issue by yeus** [javascriptdata/danfojs#387]
**Is your feature request related to a problem? Please describe.**
I am trying to get danfojs running with quasar + webpack5 + vue3. Its a pain, because danfojs apparently relies on the nodejs api.

I have no idea about the internals of danfojs  but I do get these errors here when trying to compile with the configuration below:

danfojs:  1.0.2
quasar: v2.5.5
vue: 3.2.31

I solved it by doing things like this in the webpack configuration but it is kind of a dirty workaround and
will definitly care away new programmers that want to use danfojs in frontend applications using react/vue/angular and the likes...

``` javascript
extendWebpack (cfg, {isServer, isClient}) {
          cfg.module.rules.push ({
            resolve: {
              fallback: {fs: false, net: false, tls: false}
            }
          })
}

chainWebpack ( chain ) {
        // also needs: 
        //    yarn add --dev node-polyfill-webpack-plugin browserify-zlib
        const nodePolyfillWebpackPlugin = require('node-polyfill-webpack-plugin')
        chain.plugin('node-polyfill').use(nodePolyfillWebpackPlugin)
        chain.resolve.alias.set('zlib', 'browserify-zlib')
}
```

**Describe the solution you'd like**
Remove dependencies on nodejs API in order to support the browser and SPA such as Vue/React/Angular in a better way.

**Describe alternatives you've considered**
Change the package to dataforge, but I need some features that aren't available there...

**Additional context**

here is a short explanation of whats going on:
https://quasar.dev/start/upgrade-guide#nodejs-polyfills

and here a similar issue for another library:
https://github.com/quasarframework/quasar/issues/9780

**Comment by risenW** [comment]
@yeus Danfojs is currently bundled for and able to run browser side, so I'm sure this has to do with your Webpack config. See our webpack config for building the browser side version here: https://github.com/javascriptdata/danfojs/blob/dev/src/danfojs-browser/webpack.config.js
