### ISSUE TITLE
Danfo-js for React Native

### ISSUE THREAD

**Issue by RohithBhandaru** [javascriptdata/danfojs#397]
**Is your feature request related to a problem? Please describe.**
I'm looking for using Danfojs in my react native app. But certain modules used by Danfojs, for ex, fs are not compatible with React Native environment.

**Describe the solution you'd like**
Ability to use Danfojs in react native apps

**Describe alternatives you've considered**

**Additional context**

And thank you for bringing this pandas like module to js community!

**Comment by risenW** [comment]
Thanks for raising this issue. I’ll work on a update. This is similar to #387

**Comment by risenW** [comment]
Fixed in #438
