### ISSUE TITLE
Getting Started suggests you need to choose up front if you're building for Node vs webplatform/browser

### ISSUE THREAD

**Issue by danbri** [javascriptdata/danfojs#399]
It would be useful to be able to import a single core/base module so that platform agnostic JS projects don't need to choose one or the other of your platform-specific packages to import.  As far as I can tell, https://github.com/javascriptdata/danfojs/tree/dev/src/danfojs-base isn't intended to be used this way.

I appreciate that these two JS environments have big differences (access to DOM, GPU etc., amongst others), but it would be good to have something in your Guide for writing code that is as agnostic as possible about Node vs browser.

**Comment by risenW** [comment]
> It would be useful to be able to import a single core/base module so that platform agnostic JS projects don't need to choose one or the other of your platform-specific packages to import. As far as I can tell, https://github.com/javascriptdata/danfojs/tree/dev/src/danfojs-base isn't intended to be used this way.
> 
> I appreciate that these two JS environments have big differences (access to DOM, GPU etc., amongst others), but it would be good to have something in your Guide for writing code that is as agnostic as possible about Node vs browser.

Thanks for the suggestion. We will consider it. If you have any pointers and tips, I’d love to hear them as well.
