### ISSUE TITLE
ES6 Style import

### ISSUE THREAD

**Issue by psytron** [javascriptdata/danfojs#402]
More apps are using modern standard ES6 style import:
e.g. import { DataFrame } from "danfojs.js" 

This doesn't work with danfojs and any attempts to use systems like esinstall.js or esbuild.js fails with error:
__polyfill-node:assert-adfeef41.js:2460 Uncaught TypeError: Cannot read properties of undefined (reading 'prototype')
    at Object.inherits (__polyfill-node:assert-adfeef41.js:2460:46)
    at danfojs.js:157527:8

**Comment by risenW** [comment]
> I'm also really interested in an import as ES module. Coincidentally, I was working on a [fork](https://github.com/JanKaul/danfojs/tree/esmodule) to introduce a `"module"` entry point for danfo. It creates two bundles:
> 
> lib/bundle.js lib/bundle-esm.js
> 
> @risenW , if you think this would work for danfo then I'm gonna make a pull request.

@JanKaul Yes please, go ahead.

**Comment by risenW** [comment]
Fixed in #403 , and pushed new release (v1.0.3)
