### ISSUE TITLE
Empty DataFrames are always created without columns information

### ISSUE THREAD

**Issue by igonro** [javascriptdata/danfojs#412]
https://github.com/javascriptdata/danfojs/blob/df757838b812766c813489942401b424d034d62e/src/danfojs-base/core/generic.ts#L75

In this line, I see that when a DataFrame is created with empty data, the columns information is not passed to the DataFrame object.

I think this approach is not correct, because empty dataframes can also have useful information such as columns names or columns types. I will start to create a Pull Request with some tests in order to implement this, and maybe we can discuss if this could be added, but I think that DanfoJS already has a very good and solid design/structure to implement this without too much struggling.

Also not having empty dataframes creates unexpected errors (at least the ones who are used to Pandas) when filtering data.

For example, with DanfoJS we get this:
```js
var data = {
    worker: ["david", "david", "john", "alice", "john", "david"],
    day: ["monday", "tuesday", "wednesday", "thursday", "friday", "friday"],
    hours: [5, 6, 2, 8, 4, 3],
};

var df = new dfd.DataFrame(data);

df.loc({rows: df["day"].eq("friday")}).groupby(["worker"]).count().print();
// ╔════════════╤═══════════════════╤═══════════════════╤═══════════════════╗
// ║            │ worker            │ day_count         │ hours_count       ║
// ╟────────────┼───────────────────┼───────────────────┼───────────────────╢
// ║ 0          │ john              │ 1                 │ 1                 ║
// ╟────────────┼───────────────────┼───────────────────┼───────────────────╢
// ║ 1          │ david             │ 1                 │ 1                 ║
// ╚════════════╧═══════════════════╧═══════════════════╧═══════════════════╝

df.loc({rows: df["day"].eq("saturday")}).groupby(["worker"]).count().print();
// Uncaught TypeError: r[0] is undefined
//     getRowAndColValues utils.ts:172
//     loadObjectIntoNdframe generic.ts:143
//     e generic.ts:83
//     t frame.ts:122
//     toDataFrame groupby.ts:412
//     operations groupby.ts:418
//     count groupby.ts:431
```

While in Pandas we get this:
```python
import pandas as pd

data = {
    "worker": ["david", "david", "john", "alice", "john", "david"],
    "day": ["monday", "tuesday", "wednesday", "thursday", "friday", "friday"],
    "hours": [5, 6, 2, 8, 4, 3],
}

df = pd.DataFrame(data)

print(df.loc[df["day"] == "friday"].groupby(["worker"]).count())
#         day  hours
# worker
# david     1      1
# john      1      1

print(df.loc[df["day"] == "saturday"].groupby(["worker"]).count())
# Empty DataFrame
# Columns: [day, hours]
# Index: []
```

**Comment by risenW** [comment]
> https://github.com/javascriptdata/danfojs/blob/df757838b812766c813489942401b424d034d62e/src/danfojs-base/core/generic.ts#L75
> 
> In this line, I see that when a DataFrame is created with empty data, the columns information is not passed to the DataFrame object.
> 
> I think this approach is not correct, because empty dataframes can also have useful information such as columns names or columns types. I will start to create a Pull Request with some tests in order to implement this, and maybe we can discuss if this could be added, but I think that DanfoJS already has a very good and solid design/structure to implement this without too much struggling.
> 
> Also not having empty dataframes creates unexpected errors (at least the ones who are used to Pandas) when filtering data.
> 
> For example, with DanfoJS we get this:
> 
> ```js
> var data = {
>     worker: ["david", "david", "john", "alice", "john", "david"],
>     day: ["monday", "tuesday", "wednesday", "thursday", "friday", "friday"],
>     hours: [5, 6, 2, 8, 4, 3],
> };
> 
> var df = new dfd.DataFrame(data);
> 
> df.loc({rows: df["day"].eq("friday")}).groupby(["worker"]).count().print();
> // ╔════════════╤═══════════════════╤═══════════════════╤═══════════════════╗
> // ║            │ worker            │ day_count         │ hours_count       ║
> // ╟────────────┼───────────────────┼───────────────────┼───────────────────╢
> // ║ 0          │ john              │ 1                 │ 1                 ║
> // ╟────────────┼───────────────────┼───────────────────┼───────────────────╢
> // ║ 1          │ david             │ 1                 │ 1                 ║
> // ╚════════════╧═══════════════════╧═══════════════════╧═══════════════════╝
> 
> df.loc({rows: df["day"].eq("saturday")}).groupby(["worker"]).count().print();
> // Uncaught TypeError: r[0] is undefined
> //     getRowAndColValues utils.ts:172
> //     loadObjectIntoNdframe generic.ts:143
> //     e generic.ts:83
> //     t frame.ts:122
> //     toDataFrame groupby.ts:412
> //     operations groupby.ts:418
> //     count groupby.ts:431
> ```
> 
> While in Pandas we get this:
> 
> ```python
> import pandas as pd
> 
> data = {
>     "worker": ["david", "david", "john", "alice", "john", "david"],
>     "day": ["monday", "tuesday", "wednesday", "thursday", "friday", "friday"],
>     "hours": [5, 6, 2, 8, 4, 3],
> }
> 
> df = pd.DataFrame(data)
> 
> print(df.loc[df["day"] == "friday"].groupby(["worker"]).count())
> #         day  hours
> # worker
> # david     1      1
> # john      1      1
> 
> print(df.loc[df["day"] == "saturday"].groupby(["worker"]).count())
> # Empty DataFrame
> # Columns: [day, hours]
> # Index: []
> ```

Hey @igonro You're correct, and I would gladly review a PR from you on this.

**Comment by igonro** [comment]
Hi @risenW, can you briefly explain why this line is needed? I think I may have to modify it in order to fix some tests, but I don't see the motivation behind it (and I'm sure that there is a good reason)

https://github.com/javascriptdata/danfojs/blob/c9cc17d2b8fafb3f12b35cc14f82ca2e240b4e28/src/danfojs-base/core/generic.ts#L316

Thanks!

**Comment by igonro** [comment]
Maybe @steveoni can help too answering this question(?)

Thank you very much!

**Comment by risenW** [comment]
> Hi @risenW, can you briefly explain why this line is needed? I think I may have to modify it in order to fix some tests, but I don't see the motivation behind it (and I'm sure that there is a good reason)
> 
> https://github.com/javascriptdata/danfojs/blob/c9cc17d2b8fafb3f12b35cc14f82ca2e240b4e28/src/danfojs-base/core/generic.ts#L316
> 
> Thanks!

That’s the default column name when non is provided for Series. Theoretical, Series is not suppose to have a column name though.

Does removing that break any test? If no, then modify and we can test together after your PR
