### ISSUE TITLE
addColumns and result_type: expand for apply?

### ISSUE THREAD

**Issue by joshuakoh1** [javascriptdata/danfojs#423]
Hello,

I can't seem to replicate what I can do in pandas
```
df[['B','C','D']] = df['A'].apply(lambda x: f(x), result_type='expand')
```
I found a dirty fix by accessing the values array and running a concat but there has to be a cleaner way to do this
```
function f(A){
return [A, A, A]
}
df1 = new dfd.DataFrame(df.A.apply(f).values, {columns: ['B','C','D']})
df = dfd.concat({dfList: [df, df1], axis: 1})
```

**Comment by risenW** [comment]
> Hello,
> 
> I can't seem to replicate what I can do in pandas
> 
> ```
> df[['B','C','D']] = df['A'].apply(lambda x: f(x), result_type='expand')
> ```
> 
> I found a dirty fix by accessing the values array and running a concat but there has to be a cleaner way to do this
> 
> ```
> function f(A){
> return [A, A, A]
> }
> df1 = new dfd.DataFrame(df.A.apply(f).values, {columns: ['B','C','D']})
> df = dfd.concat({dfList: [df, df1], axis: 1})
> ```

JavaScript is different from the Python language in many ways, as such most features won't translate one-to-one. What you did with Danfo is not dirty.
