### ISSUE TITLE
terminated by signal SIGILL (Illegal instruction)

### ISSUE THREAD

**Issue by qwang1113** [javascriptdata/danfojs#425]
**Describe the bug**
example code 
`
const dfd = require('danfojs-node');

console.log(dfd)
`

**To Reproduce**
execute the above code, then fish output error: `fish: Job 1, 'node test.js' terminated by signal SIGILL (Illegal instruction)`

**Screenshots**
<img width="679" alt="image" src="https://user-images.githubusercontent.com/15064266/159202130-b61f4f05-d2db-429e-97f8-d5561e815bd4.png">

**Desktop (please complete the following information):**
macbook pro m1

**Additional context**
maybe m1 macbook error?

**Comment by risenW** [comment]
Similar to https://github.com/javascriptdata/danfojs/issues/431

**Comment by AhmedBenHadj2** [comment]
Hey @risenW ,

It's not similar to https://github.com/javascriptdata/danfojs/issues/431, It's likely due to the new M1 that's not working with the library.
