### ISSUE TITLE
JavaScript heap out of memory when importing danfojs library

### ISSUE THREAD

**Issue by akhlaq-ha** [javascriptdata/danfojs#431]
**Node-version:14.5.0
Dependencies attached in screenshot**

Hi,
i am using danfojs in React Application  like so :

```
var dfd = require('danfojs');  

const { sheetData } = useContext(SheetDataContext);

useEffect(()=>{

    let df1 = new dfd.DataFrame(rawSheet)

},[])
```
but project fails at compiling as shown in screen shot
Let me know what am i doing wrong.
Thanks

![image](https://user-images.githubusercontent.com/77789142/160627420-40d3767b-9258-4fa7-883b-7d1f420dc704.png)

![image](https://user-images.githubusercontent.com/77789142/160624683-61cd6ad0-ffac-4658-a71a-03d5138252f4.png)

**Comment by risenW** [comment]
Thanks for reporting, looking into this now. Can you provide more issues like which system you're using, React version, and Danfojs version
