### ISSUE TITLE
Basic vectorized operations lacking

### ISSUE THREAD

**Issue by Saran33** [javascriptdata/danfojs#433]
Hi there, thank you for this great library. As long-time Pandas user, I was really excited to try Danfo. However, after reading the docs and buying your book, I’m quite disappointed to have to revert back to using JavaScript arrays and objects for element-wise logic. Is there any way to perform basic conditional logic between rows (and subsequent creation of new series) as vectorized operations? 

E.g if (df[‘A’] > df[‘B’]) { df[‘C’] = df[‘A’] - df[‘b’] } , as per the intuitive Pandas-style syntax.

**Comment by risenW** [comment]
Hi @Saran33 JavaScript as a languae does not support operator overloading like Python, so this `(df[‘A’] > df[‘B’]) { df[‘C’] = df[‘A’] - df[‘b’]} ` won't work. You can do the following instead using methods:

```javascript

df[‘A’].gt(df[‘B’])

df[‘C’] = df['A'].sub( df[‘b’] )
```

See: https://danfo.jsdata.org/api-reference/series/series.gt and https://danfo.jsdata.org/api-reference/series/series.sub
