### ISSUE TITLE
sample.toJSON() broke in 1.0.5

### ISSUE THREAD

**Issue by odjhey** [javascriptdata/danfojs#439]
**Describe the bug**
`sample.toJSON()` broke in 1.0.5
looks like the `frame` returned by `df.sample()` is from `base` - `src/danfojs-base/core/frame.ts` and not from the `node` one. 

**To Reproduce**
```ts
// install 1.0.5
import {DataFrame} from 'danfojs-node'

const df = new DataFrame([{a: 1}, {b: 2}])
console.log(df.toJSON())
const sample = await df.sample(1)
console.log(sample.toJSON())
```

**Expected behavior**
`sample.toJSON()` should return
```
[ { a: 1 } ]
```

**Screenshots**
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/8198939/161428577-8b702dbe-b4ed-4755-8098-b34f8a97bd99.png">

**Desktop (please complete the following information):**
 - OS: MacOS 11.5.2 M1 2020
 - Browser: Node v17.7.2
 - Version v17.7.2

**Smartphone (please complete the following information):**

**Additional context**

**Comment by odjhey** [comment]
hmm, i think any method that returns the `base-df` (`sample, head, add, etc`) will not include the `io` functions found in `node-df/browser-df` which include `toCSV, toJSON, toExcel`

im directly using the exported `toJSON` for now (below example)

```ts
import {DataFrame, toJSON} from 'danfojs-node'

const df = new DataFrame([{a: 1}, {b: 2}])
console.log(df.toJSON())
const sample = await df.sample(1)

// console.log(sample.toJSON()) // <--- replace baseDf.toJSON() with the one from import {toJSON} from 'danfojs-node'
console.log(toJSON(sample))

```

**Comment by risenW** [comment]
Thanks @odjhey for catching and reporting this. I just realized as well. Working on it now.

**Comment by risenW** [comment]
FIXED in https://github.com/javascriptdata/danfojs/pull/440

**Comment by odjhey** [comment]
hi @risenW, super thanks! I wouldve sent a PR for a fix but my powers was not enough hehe. BTW! Thanks for working on danfojs, really helping our small team big time! :) We'll find ways to contribute better in the future! Again, super thanks ".)👍🏼

**Comment by risenW** [comment]
> hi @risenW, super thanks! I wouldve sent a PR for a fix but my powers was not enough hehe. BTW! Thanks for working on danfojs, really helping our small team big time! :) We'll find ways to contribute better in the future! Again, super thanks ".)👍🏼

No worries @odjhey Thanks for using danfojs, and sending issues! Much appreciated as well.
