### ISSUE TITLE
Can all the source code put into just one file?

### ISSUE THREAD

**Issue by LastsForever** [javascriptdata/danfojs#448]
I hope to use this project in WPS Office JS Macro, but the only way to use it at present is to copy the whole source code into a module in WPS. If all the source code in this project were in just one file, it would be much more convenient to use it.

**Comment by risenW** [comment]
You can grab the single bundled JS file from : https://www.jsdelivr.com/package/npm/danfojs?path=lib

**Comment by LastsForever** [comment]
> You can grab the single bundled JS file from : https://www.jsdelivr.com/package/npm/danfojs?path=lib

Thank you.
