### ISSUE TITLE
Any simple way to invert a boolean mask ? ("~" operator in Pandas)

### ISSUE THREAD

**Issue by Achuttarsing** [javascriptdata/danfojs#453]
Hi ! First, thank you for your amazing work ! 

I would like to remove rows containing Na in a specific column of a DataFrame. I'm new to Danfojs so maybe I'm missing something... There is no **_notNa()_** operator so I'm trying `df.query( df['specific_column'].isNa().eq(false) )` but it gives an error.

I'm wondering if there is an easy way to do this.

I'm not thinking about a notNa() function, but more generally a way to revert a boolean mask like the **_tilde (~) operator_** in Pandas. This operator **_means bitwise not_**, inverting `False` to `True` and `True` to `False`. 

Ex : `df[~df["name"].str.contains("ick")]` selects all the rows whose _'name'_ column does not contain "ick".

Thank you for your help

**Comment by shrshk** [comment]
I have a similar problem, I want to do something like 
 df = df.loc({ rows: df['id'].eq(['a', 'b']) })
however this does not work, another option is to do 
df = df.loc({ rows: df['id'].eq('a') })
df = df.loc({ rows: df['id'].eq('a') })
and merge them but that would be very expensive

**Comment by controversial** [comment]
Did you find a solution for this?

**Comment by risenW** [comment]
Hi, you could use the applyMap function to invert each element after check the nan property. See  https://danfo.jsdata.org/api-reference/dataframe/dataframe.apply_map

**Comment by controversial** [comment]
I ended up using `df.iloc({ rows: df['specific_column'].isNa().eq(new Array(df.shape[0]).fill(false)) })` (since `eq` supports an array of boolean values but not a single boolean value).
