### ISSUE TITLE
No Error Thrown If File Path Is Invalid For df.readCSV?

### ISSUE THREAD

**Issue by guekling** [javascriptdata/danfojs#456]
**Describe the bug**
When an invalid filepath is passed into `df.readCSV`, no errors are thrown and the request is never resolved. Are we supposed to check for validity of filepath ourselves before passing it into the function?

**To Reproduce**
Use the following code:
```
import * as dfd from "danfojs-node";

dfd.readCSV("invalid-filepath.csv")
  .then((df) => {
    // some code
  })
  .catch((error) => {
    console.log(error)
  })
```

**Expected behavior**
Should throw an error.

**Additional context**
Using `danfojs-node` v1.1.1

**Comment by risenW** [comment]
Fixed in https://github.com/javascriptdata/danfojs/pull/503

**Comment by matB7723** [comment]
I encounter the same issue using "danfojs" v1.1.2 in Angular. Has this been fixed for node-only or browser as well?
