### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by applegrew** [javascriptdata/danfojs#471]
**Describe the bug**
I am getting JS error in danfo js for a specific scenario - `TypeError: Cannot read properties of undefined (reading '0')`.

The stack trace is as below.

    TypeError: Cannot read properties of undefined (reading '0')
        at _iloc (https://tksp5f.csb.app/node_modules/danfojs/dist/danfojs-base/core/indexing.js:150:56)
    
        at DataFrame.query (https://tksp5f.csb.app/node_modules/danfojs/dist/danfojs-base/core/frame.js:2295:43)

**To Reproduce**
1. Go to https://codesandbox.io/s/sleepy-mcclintock-tksp5f?file=/src/index.js
2. The sample code in that url will run automatically.
3. Check browser console.
4. You will notice the above JS error.

**Expected behavior**
There should be no JS error.

**Additional context**
Using version 1.1.1 of Danfo JS. 

<img width="1792" alt="Screenshot 2022-07-18 at 4 20 33 PM" src="https://user-images.githubusercontent.com/434574/179496424-1ad834ab-c157-4a58-91ff-f4965206a735.png">

**Comment by JagdishKolhe** [comment]
I think danfojs has some tight integration of index values while querying. Please try to resent the index, it might solve the issue.
df1.resetIndex({ inplace: true })

**Comment by kburchfiel** [comment]
I wrestled for quite a bit with the query function before recognizing that my custom index was the issue. Perhaps a note on the need to reset the index could be added to the `query` documentation page?
