### ISSUE TITLE
`DataFrame.apply` function output is inconsistent

### ISSUE THREAD

**Issue by applegrew** [javascriptdata/danfojs#472]
**Describe the bug**
`DataFrame.apply` is supposed to return `Series` however it returns a `DataFrame` if the original `DataFrame` contains no rows.

**To Reproduce**
1. Go to https://codesandbox.io/s/sweet-voice-w2n0bx?file=/src/index.js
2. The code should run on its own.
3. Open the console and notice the outputs.
4. When `DataFrame` contains rows then `$isSeries` is true else it is false.

**Expected behavior**
`apply` should always return a `Series`.

**Additional context**
Using version 1.1.1 of Danfo JS.

**Comment by risenW** [comment]
> 1. https://codesandbox.io/s/sweet-voice-w2n0bx?file=/src/index.js

Hi, this is the intended behavior. That is, the result of apply can be a Series or DataFrame depending on the result of the callable function passed to it. In terms of an empty DataFrame, there is no result to compute, hence it returns a DataFrame.
