### ISSUE TITLE
dataframe.get_groups is not working in nodeJS

### ISSUE THREAD

**Issue by Parthibanjj** [javascriptdata/danfojs#476]
I Just tried to use the examples given in the site 
link : https://danfo.jsdata.org/api-reference/groupby/groupby.get_groups

When I try to run it it says, 

grp.get_groups(["foo"]).print()
    ^
TypeError: grp.get_groups is not a function 

Below is the code i copied and tried

let data ={'A': ['foo', 'bar', 'foo', 'bar',
                'foo', 'bar', 'foo', 'foo'],
           'B': ['one', 'one', 'two', 'three',
                'two', 'two', 'one', 'three'],
           'C': [1,3,2,4,5,2,6,7],
           'D': [3,2,4,1,5,6,7,8]
        }

let df1 = new dfd.DataFrame(data)

let grp = df1.groupby(["A"])

grp.get_groups(["foo"]).print()

grp.get_groups(["bar"]).print()

**Comment by steveoni** [comment]
@Parthibanjj  https://github.com/javascriptdata/danfojs/issues/444

**Comment by Parthibanjj** [comment]
Its working now.. Thanks
