### ISSUE TITLE
`Series.valueCounts` run into error when all the value are unique

### ISSUE THREAD

**Issue by kikiatproton** [javascriptdata/danfojs#484]
**Describe the bug**
`Series.valueCounts` run into error when all the value are unique

**To Reproduce**
1. Parse a .csv file
```
dfd.readCSV(file).then((df) => {
    const sf = df[df.columns[0]];
    sf.valueCounts().print();
})
```
2. See error
`IndexError: Row index must contain unique values`

**Expected behavior**
Should display all valueCount

**Screenshots**
<img width="501" alt="Screen Shot 2022-08-05 at 6 01 34 PM" src="https://user-images.githubusercontent.com/105805886/183217269-ec9081b2-4918-4c17-a7be-0f6b7fae677e.png">

**Comment by risenW** [comment]
> **Describe the bug** `Series.valueCounts` run into error when all the value are unique
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Parse a .csv file
> 
> ```
> dfd.readCSV(file).then((df) => {
>     const sf = df[df.columns[0]];
>     sf.valueCounts().print();
> })
> ```
> 
> 2. See error
>    `IndexError: Row index must contain unique values`
> 
> **Expected behavior** Should display all valueCount
> 
> **Screenshots** <img alt="Screen Shot 2022-08-05 at 6 01 34 PM" width="501" src="https://user-images.githubusercontent.com/105805886/183217269-ec9081b2-4918-4c17-a7be-0f6b7fae677e.png">

This error is coming from incorrect DataFrame selection at `df[df.columns[0]];` not valueCounts.

**Comment by ryan-williams** [comment]
I believe `df[df.columns[0]]` is fine, in general.

Here are some simple examples showing the problem with `Series.valueCounts`:
```javascript
new Series(["2021-01", "2021-02"]).valueCounts()
// Error: IndexError: Row index must contain unique values
```

Here's a small example:

```javascript
new Series(["1", "1_"]).valueCounts()
// Error: IndexError: Row index must contain unique values
```

It seems to occur when two different elements begin with the same integer, but at least one is a string with a suffix that differs from the other.

Here's some more examples:
```javascript
let elems = [ 1, '1', '1_', ]
for (let e1 of elems) {
    for (let e2 of elems) {
        let arr = [ e1, e2 ]
        let success = true
        try {
            new Series(arr).valueCounts()
        } catch {
            success = false
        }
        console.log(`new Series([${arr.map(a => typeof a === 'string' ? `"${a}"` : `${a}`).join(', ')}]): ${success ? "✅" : "❌"}`)        
    }
}
// new Series([1, 1]): ✅
// new Series([1, "1"]): ✅
// new Series([1, "1_"]): ❌
// new Series(["1", 1]): ✅
// new Series(["1", "1"]): ✅
// new Series(["1", "1_"]): ❌
// new Series(["1_", 1]): ❌
// new Series(["1_", "1"]): ❌
// new Series(["1_", "1_"]): ✅
```
