### ISSUE TITLE
Browser excel output docs don't match types

### ISSUE THREAD

**Issue by matt-erhart** [javascriptdata/danfojs#491]
https://github.com/javascriptdata/danfojs/blob/a8d14d45bca2a50836a6e2d6ec1a77582c42993a/src/danfojs-base/shared/types.ts#L409

https://danfo.jsdata.org/api-reference/dataframe/dataframe.to_excel#convert-dataframe-to-excel-and-download-the-file-in-a-browser
```ts
let data = {
    Abs: [20.2, 30, 47.3],
    Count: [34, 4, 5],
    "country code": ["NG", "FR", "GH"],
};

let df = new dfd.DataFrame(data);

df.toExcel({ fileName: "testOut.xlsx", download: true }); //deprecated, docs have download, but types appear not to
dfd.toExcel(df, { fileName: "testOut.xlsx", download: true}); //current, docs have download, but types appear not to
```

When I try to run it with  download: true, I get the following error: ```Uncaught Error: Module "fs" has been externalized for browser compatibility. Cannot access "fs.writeFileSync" in client code.``` but I'm not sure if that's a danfo issue or a vitejs issue at the moment. dfd.toCSV works as expected.

**Comment by risenW** [comment]
> 

Thanks for the catch. Docs have been updated, as you do not need the download argument.

For browser downloads, the toExcel function calls xlsx's internal writeFile function, and this will detect the environment and automatically open a download file window.
