### ISSUE TITLE
Cannot access columns populated with Date objects 

### ISSUE THREAD

**Issue by nholmes3** [javascriptdata/danfojs#509]
**Describe the bug**
When trying to access a column that is populated with Date objects, the following error is thrown

```
File format not supported!
```

**To Reproduce**
```
const df = new dfd.DataFrame([{'foo': 'bar'}]);
df.addColumn('dateColumn', [new Date()], {inplace: true});
const dateColumn = df.column('dateColumn');
```

This is a result of the data not passing any of the conditionals in the [NDframe constructor](https://github.com/javascriptdata/danfojs/blob/dev/src/danfojs-base/core/generic.ts#L62)

My suggestion is to update either of these conditions to include a check for Date objects:
https://github.com/javascriptdata/danfojs/blob/dev/src/danfojs-base/core/generic.ts#L79
https://github.com/javascriptdata/danfojs/blob/dev/src/danfojs-base/core/generic.ts#L83

**Expected behavior**
The column should be returned correctly without error

**Desktop (please complete the following information):**
 - OS: Node 16 Docker Image (FROM node:16)
 - Version 1.1.1

**Comment by nholmes3** [comment]
> hi, you can try : const dateColumn = df.column('dateColumn').$data;

Hi @jaydeep-work, thank you for posting your workaround!  I am currently converting the dates to strings before adding them to the DF, but both of these workarounds are less desirable than danfo being able to handle Date objects in the first place.

**Comment by risenW** [comment]
I've been working on adding default support for Datetime columns. This will get pushed in the new release.
