### ISSUE TITLE
danfojs package not recognized using Vue 3+Vite

### ISSUE THREAD

**Issue by bkawakami** [javascriptdata/danfojs#514]
**Describe the bug**
danfojs package not recognized using Vue 3+Vite

**To Reproduce**
- Create Vue 3+Vite project
```bash
npm init vue@latest
```

- Install danfojs package
```bash
npm i --save danfojs
```

- Add to HomeView.vue danfojs import
```vue
<script setup lang="ts">
import * as dfd from "danfojs"
</script>
```

**Expected behavior**
danfojs be founded by vite

**Screenshots**
<img width="911" alt="Screenshot 2022-11-01 at 17 36 16" src="https://user-images.githubusercontent.com/1881935/199336519-e4dc5ca0-b332-415e-82d7-dc2c51f28c3f.png">

**Comment by bkawakami** [comment]
Someone? 😔

**Comment by pensono** [comment]
I ran into the same problem. Fixed this by downgrading from `1.1.2` to `1.1.1`

Is the issue related to how `bundle.js` and `bundle-esm.js` are mismatched here?
https://github.com/javascriptdata/danfojs/blob/fe37f10c83265e22a645e9921e0d880b9b75a180/src/danfojs-browser/package.json#L7
https://github.com/javascriptdata/danfojs/blob/a8d14d45bca2a50836a6e2d6ec1a77582c42993a/src/danfojs-browser/webpack.config.js#L15

Breaking change?
https://github.com/javascriptdata/danfojs/pull/447/files

I have made a PR

**Comment by bkawakami** [comment]
Thanks @pensono, in version 1.1.1 everthing works fine!

**Comment by ayush-seth** [comment]
I had the same problem, instead of rolling back to old version, you can also change the import statement to import the file directly from where it is defined instead of importing it from main module. For example if you want to use `DataFrame`-

This doesn't work
```
import { DataFrame } from 'danfojs';
```

But, this will work: 
```
import { DataFrame } from 'danfojs/dist/danfojs-base'
```

You can use this as a workaround until the `package.json` file is fixed on main

**Comment by hopezh** [comment]
May I ask if this issue has been resolved?
